import { createHash } from 'node:crypto';
import { mkdir, writeFile } from 'node:fs/promises';
import { readFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { MONUMENTS, type Monument } from '../../src/data/monuments.ts';
import { prepareCatalogImport } from './catalog.ts';

export const STATIC_CATALOG_SOURCE = 'static_catalog';
export const STATIC_CATALOG_SQL_PATH =
  'docs/migration/generated/static-catalog-import.sql';
export const STATIC_CATALOG_EVIDENCE_PATH =
  'docs/migration/evidence/static-catalog-import.json';

const sha256 = (value: string) =>
  createHash('sha256').update(value).digest('hex');
const sqlText = (value: string) => `'${value.replaceAll("'", "''")}'`;

function translations(monument: Monument) {
  const spanish = monument.translations?.es;
  const rows = [
    { locale: 'en', name: monument.name, description: monument.desc },
    { locale: 'es', name: spanish?.name, description: spanish?.desc },
  ];
  for (const row of rows) {
    if (!row.name?.trim() || !row.description?.trim()) {
      throw new Error(
        `${monument.id} is missing ${row.locale} name or description`
      );
    }
  }
  return rows as Array<{
    locale: 'en' | 'es';
    name: string;
    description: string;
  }>;
}

export function adaptStaticCatalog(monuments: Monument[] = MONUMENTS) {
  return monuments.map((monument) => ({
    type: 'place' as const,
    legacyKey: monument.id,
    coordinates: [monument.lng, monument.lat],
    publicationState: 'draft' as const,
    translations: translations(monument),
    source: monument,
  }));
}

function buildSql(plan: ReturnType<typeof prepareCatalogImport>) {
  const staged = plan.stagedBatches.flat();
  const maps = plan.mapBatches.flat();
  const rows = staged.map((row) => ({
    ordinal: row.ordinal,
    legacyKey: row.legacyKey,
    canonicalRow: row.canonicalRow,
    rowSha256: row.rowSha256,
  }));
  const mapped = maps.map((map) => ({
    legacyKey: map.legacyKey,
    catalogId: map.catalogId,
  }));
  const manifest = plan.manifest;
  return `-- Generated by pnpm catalog:plan. Parent review is required before execution.
begin;
select pg_catalog.pg_advisory_xact_lock(pg_catalog.hashtextextended(${sqlText(`${STATIC_CATALOG_SOURCE}:places`)}, 0));

create temporary table _u4c_context(run_id uuid primary key) on commit drop;
with inserted as (
  insert into catalog_import.import_runs(source_name, source_sha256, canonical_sha256, expected_rows)
  values (${sqlText(manifest.sourceName)}, ${sqlText(manifest.sourceSha256)}, ${sqlText(manifest.canonicalSha256)}, ${manifest.expectedRows})
  on conflict (source_name, source_sha256) do nothing returning id
)
insert into _u4c_context
select id from inserted
union all
select id from catalog_import.import_runs
where source_name = ${sqlText(manifest.sourceName)} and source_sha256 = ${sqlText(manifest.sourceSha256)}
limit 1;

do $$
begin
  if not exists (
    select 1 from catalog_import.import_runs r join _u4c_context c on c.run_id = r.id
    where r.canonical_sha256 = ${sqlText(manifest.canonicalSha256)} and r.expected_rows = 9
  ) then raise exception 'U4C run manifest mismatch' using errcode = '23514'; end if;
end $$;

with source_rows as (
  select * from jsonb_to_recordset($rows$${JSON.stringify(rows)}$rows$::jsonb)
    as x("ordinal" integer, "legacyKey" text, "canonicalRow" jsonb, "rowSha256" text)
)
insert into catalog_import.staged_rows(run_id, ordinal, entity_type, legacy_key, canonical_row, row_sha256)
select c.run_id, x."ordinal", 'place', x."legacyKey", x."canonicalRow", x."rowSha256"
from source_rows x cross join _u4c_context c
on conflict (run_id, ordinal) do nothing;

with source_maps as (
  select * from jsonb_to_recordset($maps$${JSON.stringify(mapped)}$maps$::jsonb)
    as x("legacyKey" text, "catalogId" uuid)
)
insert into catalog_import.stable_id_maps(source_name, entity_type, legacy_key, catalog_id, target_table, first_run_id)
select ${sqlText(manifest.sourceName)}, 'place', x."legacyKey", x."catalogId", 'places', c.run_id
from source_maps x cross join _u4c_context c
on conflict (source_name, entity_type, legacy_key) do nothing;

insert into public.places(id, legacy_source, legacy_key, longitude, latitude, publication_state, published_at)
select m.catalog_id, m.source_name, m.legacy_key,
  (s.canonical_row->'coordinates'->>0)::double precision,
  (s.canonical_row->'coordinates'->>1)::double precision, 'draft', null
from catalog_import.staged_rows s
join _u4c_context c on c.run_id = s.run_id
join catalog_import.stable_id_maps m on m.source_name = ${sqlText(manifest.sourceName)}
  and m.entity_type = 'place' and m.legacy_key = s.legacy_key
on conflict (legacy_source, legacy_key) do update set
  longitude = excluded.longitude, latitude = excluded.latitude;

insert into public.place_translations(place_id, locale, name, description)
select m.catalog_id, t.locale, t.name, t.description
from catalog_import.staged_rows s
join _u4c_context c on c.run_id = s.run_id
join catalog_import.stable_id_maps m on m.source_name = ${sqlText(manifest.sourceName)}
  and m.entity_type = 'place' and m.legacy_key = s.legacy_key
cross join lateral jsonb_to_recordset(s.canonical_row->'translations')
  as t(locale text, name text, description text)
on conflict (place_id, locale) do update set
  name = excluded.name, description = excluded.description;

do $$
declare failures text[];
begin
  select array_remove(array[
    case when (select count(*) from catalog_import.staged_rows s join _u4c_context c on c.run_id=s.run_id) <> 9 then 'staged' end,
    case when (select count(*) from catalog_import.import_rejects r join _u4c_context c on c.run_id=r.run_id) <> 0 then 'rejects' end,
    case when exists (select 1 from catalog_import.staged_rows s join _u4c_context c on c.run_id=s.run_id full join catalog_import.stable_id_maps m on m.source_name=${sqlText(manifest.sourceName)} and m.entity_type='place' and m.legacy_key=s.legacy_key where s.legacy_key is null or m.legacy_key is null) then 'maps' end,
    case when exists (select 1 from catalog_import.staged_rows s join _u4c_context c on c.run_id=s.run_id full join public.places p on p.legacy_source=${sqlText(manifest.sourceName)} and p.legacy_key=s.legacy_key where s.legacy_key is null or p.legacy_key is null) then 'places' end,
    case when (select count(*) from public.place_translations t join public.places p on p.id=t.place_id where p.legacy_source=${sqlText(manifest.sourceName)}) <> 18 or exists (select 1 from public.place_translations t join public.places p on p.id=t.place_id where p.legacy_source=${sqlText(manifest.sourceName)} and t.locale not in ('en','es')) then 'translations' end,
    case when exists (select 1 from catalog_import.staged_rows s join _u4c_context c on c.run_id=s.run_id join public.places p on p.legacy_source=${sqlText(manifest.sourceName)} and p.legacy_key=s.legacy_key join catalog_import.stable_id_maps m on m.source_name=p.legacy_source and m.entity_type='place' and m.legacy_key=p.legacy_key where p.id<>m.catalog_id or p.longitude<>(s.canonical_row->'coordinates'->>0)::double precision or p.latitude<>(s.canonical_row->'coordinates'->>1)::double precision or not (s.canonical_row->'source' ?& array['dist','emoji','audioDuration','type','image','country','city','currency'])) then 'content' end
  ], null) into failures;
  if cardinality(failures) > 0 then raise exception 'U4C reconciliation failed: %', failures using errcode='23514'; end if;
end $$;

select catalog_import.finalize_run(c.run_id, ${sqlText(manifest.canonicalSha256)}, 9, 0,
  (select count(*)::integer from catalog_import.stable_id_maps m where m.first_run_id=c.run_id))
from _u4c_context c;

select jsonb_build_object(
  'run_id', r.id, 'source_name', r.source_name, 'source_sha256', r.source_sha256,
  'canonical_sha256', r.canonical_sha256, 'staged_count', q.accepted_count,
  'reject_count', q.rejected_count, 'mapped_count', q.mapped_count,
  'place_count', 9, 'translation_count', 18, 'publication_states', 'preserved_on_retry'
) as u4c_receipt
from catalog_import.import_runs r join catalog_import.receipts q on q.run_id=r.id
join _u4c_context c on c.run_id=r.id;
commit;
`;
}

export function buildStaticCatalogPlan(
  monuments: Monument[] = MONUMENTS,
  existingMaps: Parameters<typeof prepareCatalogImport>[2] = []
) {
  const sourceRows = adaptStaticCatalog(monuments);
  const bytes = Buffer.from(JSON.stringify(sourceRows));
  const plan = prepareCatalogImport(STATIC_CATALOG_SOURCE, bytes, existingMaps);
  const sql = buildSql(plan);
  const evidence = {
    schema: 'itmap.static-catalog-import-evidence/v1',
    generatedAt: null,
    executionStatus: 'pending_parent_review',
    manifest: plan.manifest,
    counts: {
      staged: 9,
      rejected: 0,
      mapped: null,
      places: 9,
      translations: 18,
    },
    stableMaps: plan.mapBatches.flat(),
    sql: { path: STATIC_CATALOG_SQL_PATH, sha256: sha256(sql) },
    receipt: null,
    reconciliation: {
      expected:
        '9 staged/0 rejected; receipt mapped_count=current run first_run_id count (9 fresh, 0 all reused); exact source/map/place/locale parity; non-draft publication preserved',
      executed: false,
    },
  };
  return { plan, sql, evidence };
}

export function deterministicEvidence(
  evidence: ReturnType<typeof buildStaticCatalogPlan>['evidence']
) {
  return {
    schema: evidence.schema,
    manifest: evidence.manifest,
    counts: evidence.counts,
    stableMaps: evidence.stableMaps,
    sql: evidence.sql,
    expectedReconciliation: evidence.reconciliation.expected,
  };
}

export async function generateStaticCatalogArtifacts(root = process.cwd()) {
  const result = buildStaticCatalogPlan();
  let evidence: unknown = result.evidence;
  try {
    const existing = JSON.parse(
      await readFile(`${root}/${STATIC_CATALOG_EVIDENCE_PATH}`, 'utf8')
    );
    if (existing.executionStatus === 'executed') {
      if (
        JSON.stringify(deterministicEvidence(existing)) !==
        JSON.stringify(deterministicEvidence(result.evidence))
      ) {
        throw new Error('Executed evidence has deterministic drift');
      }
      evidence = existing;
    }
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code !== 'ENOENT') throw error;
  }
  await mkdir(`${root}/docs/migration/generated`, { recursive: true });
  await mkdir(`${root}/docs/migration/evidence`, { recursive: true });
  await writeFile(`${root}/${STATIC_CATALOG_SQL_PATH}`, result.sql);
  await writeFile(
    `${root}/${STATIC_CATALOG_EVIDENCE_PATH}`,
    `${JSON.stringify(evidence, null, 2)}\n`
  );
  return result;
}

if (fileURLToPath(import.meta.url) === process.argv[1]) {
  const result = await generateStaticCatalogArtifacts();
  console.log(`${STATIC_CATALOG_SQL_PATH} ${result.evidence.sql.sha256}`);
}
